### ISSUE TITLE
Control connection problems

### ISSUE THREAD

**Issue by evi-pparedes** [matute14/CalculatorService#10]
If Server cannot be reached, catch exception and inform the user

![imagen](https://user-images.githubusercontent.com/50630339/160371065-24e2fa78-fff3-4984-8133-f45ac746d2d6.png)

https://github.com/matute14/CalculatorService/blob/25aa97c871f961daf6f71877bb15945aa06a6c65/CalculatorClient/Client.cs#L160

**Comment by matute14** [comment]
![image](https://user-images.githubusercontent.com/98185350/160637098-19564e82-242b-4a85-9b3d-5212b8770a39.png)
