### ISSUE TITLE
CalculatorServer doesn't open on expected port

### ISSUE THREAD

**Issue by evi-pparedes** [matute14/CalculatorService#11]
When I launch CalculatorServer, it seems to be launching on port 44385 but on the client it expects it to be on port 5000.

![imagen](https://user-images.githubusercontent.com/50630339/160374217-193f8078-e841-4218-9daf-cadb64dc87bf.png)

![imagen](https://user-images.githubusercontent.com/50630339/160374375-30199da8-dc96-403d-8d4e-2087ecc405fb.png)

Bonus points: Make it configurable via env. variables or AppSettings

**Comment by evi-pparedes** [comment]
Ok, got it working... 

![imagen](https://user-images.githubusercontent.com/50630339/160374979-b85ddb22-d3ff-4ef0-87be-b5e9c2eb82ce.png)

Make sure to clean everything you don't need from launchSettings.json and add instructions to the Readme

![imagen](https://user-images.githubusercontent.com/50630339/160375202-ad5dacc3-56c7-4293-8682-5d7630c8c857.png)

Also try to format the output into human readable text

**Comment by matute14** [comment]
![image](https://user-images.githubusercontent.com/98185350/160637302-1a1a414c-2366-4775-9a8b-863007ffdb16.png)
