### ISSUE TITLE
Make Server BaseURL configurable

### ISSUE THREAD

**Issue by evi-pparedes** [matute14/CalculatorService#5]
Try to avoid hardcoded strings in favor of constants that you can reuse.
Move the CalculatorService URL to a constant. And for bonus points, make it configurable either by [env. variables](https://www.c-sharpcorner.com/UploadFile/84c85b/understanding-environment-variables-in-C-Sharp/) or [AppSettings](https://www.c-sharpcorner.com/article/all-about-appsettings-in-asp-net-core/).

https://github.com/matute14/CalculatorService/blob/25aa97c871f961daf6f71877bb15945aa06a6c65/CalculatorClient/Client.cs#L98

**Comment by matute14** [comment]
private const string URL = "http://localhost:5000/";
