### ISSUE TITLE
Apply principle of least privilege

### ISSUE THREAD

**Issue by evi-pparedes** [matute14/CalculatorService#6]
Declare all code with the least privilege possible. All variables, functions and classes should be **private** unless they need to be used by other classes. If those members are only meant to be used in the same project declare them as **internal**. Only if a member must be exposed to other classes or externally, declare them as **public**.

[Principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege)

https://github.com/matute14/CalculatorService/blob/25aa97c871f961daf6f71877bb15945aa06a6c65/CalculatorClient/Client.cs#L14-L15

**Comment by matute14** [comment]
private static readonly HttpClient client = new HttpClient();
