### ISSUE TITLE
Bad menu formatting

### ISSUE THREAD

**Issue by evi-pparedes** [matute14/CalculatorService#7]
Menu entries appear with tabs when executed:

![imagen](https://user-images.githubusercontent.com/50630339/160363765-2738e516-8541-4dfd-a483-0f0183613023.png)

https://github.com/matute14/CalculatorService/blob/25aa97c871f961daf6f71877bb15945aa06a6c65/CalculatorClient/Client.cs#L28-L35

**Comment by matute14** [comment]
var menuOptions = "0 Salir:" + "\n1 Suma:" + "\n2 Resta:" + "\n3 Resta:" + "\n3 Multiplicacion:" + "\n4 Division:" + "\n5 Raiz cuadrada:" + "\n6 Historial:";

				Console.WriteLine(menuOptions);
